# Generated by Django 4.2 on 2023-04-25 09:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_exam_teacher_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=api.models.classroom_code_gen, max_length=6),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(default=api.models.exam_code_gen, max_length=10, primary_key=True, serialize=False),
        ),
    ]
