# Generated by Django 4.2 on 2023-04-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_classroom_code_alter_exam_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('id', 'code')},
        ),
    ]
