# Generated by Django 4.2 on 2023-04-26 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='classrooms_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
