# Generated by Django 4.2 on 2023-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='grade',
        ),
        migrations.AddField(
            model_name='answers',
            name='grading',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
